import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link'
import { Header } from '../components/Header'
import { PostCard } from '../components/PostCard'
import styles from '../styles/Blog.module.css';

import { getAllFilesMetaData } from '../lib/mdx';

export default function AboutMe({ posts }) {
  var toRender;
  if (posts.length > 0) {
    toRender = 
    (
      <div className={styles.posts}>
        {
            posts.map((post) => (
              <PostCard key={post.id} post={post}/>
            ))
        }
      </div>
  )
  }
  else {
    toRender = (<h1 className={styles.noposts}>No posts</h1>)
  }
  return (
    <div>
      <Head>
        <title>Blog - germanruzca</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <main className={styles.container}>
        <div className={styles.last_posts}>
          Ultimos posts
        </div>
        {
          toRender
        }
      </main>
    </div>
  );
};

export async function getStaticProps() {
  const posts = await getAllFilesMetaData();
  return {
    props: {posts},
  }
}