import Head from 'next/head';
import { PostCard, Header } from '../components'
import { Text, Box } from '../components/elements'
import { useMediaQuery } from '@chakra-ui/react'


import { getAllFilesMetaData } from '../lib/mdx';

export default function Blog({ posts }) {
    const [isSmallerThan450] = useMediaQuery('(max-width: 450px)');
  return (
    <div>
      <Head>
        <title>Blog - germanruzca</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <Box maxW={960} margin={isSmallerThan450 ? 20 : (0, 'auto')} display={'flex'} flexDir={'column'}>
          <Text fontSize={isSmallerThan450 ? 40 : 50} margin={0} fontWeight={700} >Posts</Text>
          <Text fontSize={18} textAlign={'justify'}>Bienvenido a mi blog, aqui podras escontrar mis escritos sobre diferentes temas que pueden resultar de tu agrado.</Text>
        <div>
          {
              posts.map((post) => (
                <PostCard key={post.id} post={post} style={{'margin-top': '20px'}}/>
              ))
          }
        </div>
      </Box>
    </div>
  );
};

export async function getStaticProps() {
  const posts = await getAllFilesMetaData();
  return {
    props: {posts},
  }
}