import Head from 'next/head';
import { Header } from '../components'
import { Box, Text, useMediaQuery } from '@chakra-ui/react'
import { IconGithub, IconLinkedinF, IconTwitter, IconInstagramF, IconGmail} from "../components/icons";
import vector from '../public/blob.svg'
import Image from 'next/image';
import png from '../public/Vector.png'
import avatar from '../public/bust-2.png'

export default function Home() {
  const [isSmallerThan450] = useMediaQuery('(max-width: 450px)')
  const [isSmallerThan800] = useMediaQuery('(max-width: 1123px)')
  return (
    <div>
      <Head>
        <title>German Ruiz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>
     <Box display={"flex"} flexDir={isSmallerThan450 ? 'column' : 'row'} width={'100%'} maxW={960} justifyContent={'space-between'} alignItems={'center'} margin={isSmallerThan450 ? 20 : (0, 'auto')}>
       <Box as={'main'} display={"flex"} width={'110%'} textAlign={isSmallerThan450 ? "center" : ''}>
         <Box>
           <Box>
             <Text margin={0} fontSize={20} fontWeight={700}>
               Hola! soy
             </Text>
             <Text margin={0} fontSize={80} fontWeight={700} fontFamily={'Roboto, sans-serif'}>
               German Ruiz
             </Text>
             <Text margin={0} fontSize={35} fontWeight={700}>
               Software Engineer
             </Text>
           </Box>
           <Box color={`#EABE7F`} fontSize={40} marginTop={40} display={"flex"} justifyContent={isSmallerThan450 ? 'center': ''}>
             <Box marginRight={20}>
               <a href={'https://github.com/germanruzca'}  target={'_blank'} rel="noreferrer">
                 <IconGithub/>
               </a>
             </Box>
             <Box marginRight={20}>
               <a href={'https://www.linkedin.com/in/germanruzca/'}  target={'_blank'} rel="noreferrer">
                 <IconLinkedinF/>
               </a>
             </Box>
             <Box marginRight={20}>
               <a href={'https://twitter.com/germanruzca'}  target={'_blank'} rel="noreferrer">
                 <IconTwitter/>
               </a>
             </Box>
             <Box marginRight={20}>
               <a href={'https://www.instagram.com/germanruzca/'} target={'_blank'} rel="noreferrer" >
                 <IconInstagramF/>
               </a>
             </Box>
             <Box marginRight={20}>
               <a href={'mailto:germanruzca@gmail.com'}>
                 <IconGmail/>
               </a>
             </Box>
           </Box>
         </Box>
       </Box>

             <Box>
               <Box width={'100%'}>
                 <Image src={avatar} height={'1200%'} width={900}/>
               </Box>
             </Box>
     </Box>
    </div>
  )
}