import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link'
import styles from '../styles/Home.module.css';
import { Header } from '../components/Header'

// import the library
import { library } from '@fortawesome/fontawesome-svg-core';
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faCode, faHighlighter } from '@fortawesome/free-solid-svg-icons';
import {
  faGithub, 
  faTwitter,
  faInstagram,
  faLinkedin
} from '@fortawesome/free-brands-svg-icons';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>German Ruiz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.container}>
        <Header/>
        <div className={styles.name}>
          <div>Germán Ruiz</div>
          <div className={styles.position}>Web Developer</div>
        </div>
        <div className={styles.icon}>
          <div>
            <a href="https://twitter.com/germanruzca" target="_blank">
              <FontAwesomeIcon icon={faTwitter}/>
            </a>
          </div>
          <div>
            <a href="https://github.com/germanruzca" target="_blank">
              <FontAwesomeIcon icon={faGithub}/>
            </a>
          </div>
          <div>
            <a href="https://www.instagram.com/germanruzca/" target="_blank">
              <FontAwesomeIcon icon={faInstagram}/>
            </a>
          </div>
          <div>
            <a href="https://www.linkedin.com/in/germanruzca/" target="_blank">
              <FontAwesomeIcon icon={faLinkedin}/>
            </a>
          </div>
        </div>
      </main>
    </div>
  )
}