import Head from 'next/head';
import {Header} from '../components/Header'

export default function Proyectos() {
  return (
    <div>
      <Head>
        <title>Proyectos - germanruzca</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <h1>Proyectos</h1>
    </div>
  );
}