import Head from 'next/head';
import styles from '../styles/Project.module.css';
import {Header} from '../components/Header'

export default function Proyectos() {
  return (
    <div>
      <Head>
        <title>Proyectos - germanruzca</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <div className={styles.container}>
        <h1 className={styles.title}>Work in progress...🔧</h1>
      </div>
    </div>
  );
}