import Head from 'next/head';
import { Header } from '../components'
import { Text, Box, useMediaQuery, Image } from "@chakra-ui/react";

export default function AboutMe() {
  const [isSmallerThan450] = useMediaQuery('(max-width: 450px)');
  return (
    <div>
      <Head>
        <title>Resumé - germanruzca</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <Box margin={isSmallerThan450 ? 20 : (0, 'auto')} maxW={960} >
        <Text fontSize={isSmallerThan450 ? 40 : 50} margin={0} fontWeight={700} >Sobre mi</Text>
        <Box marginBottom={40}>
          <Text textAlign={"justify"} lineHeight={1.5} fontSize={18}>
            Hola! soy German Ruiz, y actualmente estoy estudiando Ingeniería en Telemática en Colima, México.
          </Text>

          <Text textAlign={"justify"} lineHeight={1.5} fontSize={18}>
            Me gusta aprender nuevas cosas todos los días usando tecnologías que me gustan. Actualmente estoy interesado en tecnologías web o el desarrollo de software en general. Siempre estoy buscando que hacer, y así mejorar mis <em>skills</em> ya sean técnicos o personales. También me gusta leer, leer artículos o libros y ser alguien activo físicamente.
          </Text>

          <Text textAlign={"justify"} lineHeight={1.5} fontSize={18}>
            Estoy listo para nuevos desafíos y aprender de ellos, para poder crecer.
          </Text>

          <Text textAlign={"justify"} lineHeight={1.5} fontSize={18}>
            Puedes escribirme a mis redes sociales para estar en contacto.
          </Text>
        </Box>

        <Text fontWeight={700} fontSize={30} margin={0}>Actualmente..</Text>

        <Box>
          <Text textAlign={"justify"} lineHeight={1.5} fontSize={18}>
            <strong>Leyendo: </strong> <a href="https://www.amazon.com.mx/Atomic-Habits-Proven-Build-Break/dp/0735211299/ref=sr_1_1?__mk_es_MX=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=1852F2LCIUYLA&keywords=Atomic+Habits&qid=1650819374&sprefix=atomic+habits%2Caps%2C115&sr=8-1" target="_blank" rel="noreferrer">Atomic Habits</a> by James Clear 📖
          </Text>

          <Text textAlign={"justify"} lineHeight={1.5} fontSize={18}>
            <strong>Aprendiendo</strong>: TDD ✍🏼
          </Text>

          <Text textAlign={"justify"} lineHeight={1.5} fontSize={18}>
            <strong>Como</strong>: Software Engeneer Aprentiship en <a target={'_blank'} href={'https://salesloft.com/'}>Salesloft</a> 🧑🏻‍💻
          </Text>

          <Text textAlign={"justify"} lineHeight={1.5} fontSize={18}>
            <strong>Hago</strong>: Rails, JavaScript, PostgreSQL 💻
          </Text>
        </Box>

        <Box marginBottom={40}>
          <Text textAlign={"justify"} lineHeight={1.5} fontSize={18}>
            Puedes ver mi CV dando click <a href={'/'}>AQUI</a>
          </Text>
        </Box>
        <Box textAlign={"center"} >
          <Image width={isSmallerThan450 ? '100%' : '30%'} height={'auto'} src="https://avatars.githubusercontent.com/u/43076503?v=4" alt="me"/>
        </Box>
      </Box>
    </div>
  );
}