import Head from 'next/head';
import { Header } from '../components/Header'
import styles from '../styles/Resume.module.css'

export default function AboutMe() {
  return (
    <div>
      <Head>
        <title>Resumé - germanruzca</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <div className={styles.container}>
        <h1 className={styles.title}>About Me</h1>
        <p className={styles.about_me}>
          I&prime;m German. I&prime;m a 22 years old student from Colima, Mexico.
        </p>
        <p className={styles.about_me}>
          I like learning every day with the new technologies. I&prime;m interested in Web Technologies and Data Science, I&prime;d like to match these two areas in my carreer in the future. I&prime;m always looking for something new to do, immerse in new challenges. I also like listen to music, read articles and been fitness.
        </p>
        <p className={styles.about_me}>
          I am ready to the new challenges and grow with them.
        </p>

        <p>
          Currently Reading: <strong><a href="https://www.amazon.com.mx/Atomic-Habits-Proven-Build-Break/dp/0735211299/ref=sr_1_1?__mk_es_MX=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=1852F2LCIUYLA&keywords=Atomic+Habits&qid=1650819374&sprefix=atomic+habits%2Caps%2C115&sr=8-1" target="_blank">Atomic Habits</a></strong>
        </p>

        <div className={styles.image}>
          <img src="https://avatars.githubusercontent.com/u/43076503?v=4" alt="me"/>
        </div>
      </div>
    </div>
  );
}